pluginManagement {
    repositories {
        // 国内华为云镜像（加速）
        maven {
            name = 'HuaweiCloud'
            url = 'https://repo.huaweicloud.com/repository/maven/'
        }
        maven {
            name = 'HuaweiCloudMinecraft'
            url = 'https://repo.huaweicloud.com/repository/minecraft/'
        }

        // ★ ForgeGradle 插件来源
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }

        // ★ Mixin Gradle 插件来源
        maven {
            name = 'SpongePowered'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }

        // ★ Parchment 映射来源
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org'
        }

        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'create_hand_made'